# Generated by Django 2.2.2 on 2019-07-04 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autores', models.CharField(max_length=250)),
                ('palavras_chaves', models.CharField(max_length=500, null=True)),
                ('data_do_documento', models.CharField(max_length=100)),
                ('editor', models.CharField(max_length=100)),
                ('citacao', models.IntegerField()),
                ('resumo', models.TextField()),
                ('abstract', models.TextField()),
                ('descricao', models.TextField()),
                ('data_de_publicacao', models.DateField(default=datetime.date.today)),
                ('link', models.CharField(max_length=999, null=True)),
            ],
        ),
    ]
