# Generated by Django 2.2.2 on 2019-06-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='palavras_chaves',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
